-- Auth akisi entegrasyon testleri (pg-editor F5)
local h = require("helpers.init")

describe("auth flow (integration)", function()
  local admin
  setup(function()
    h.reset_db()
    admin = h.login_admin()
  end)

  it("basarili login: token cifti, user, permissions", function()
    local res = h.request("POST", "/auth/login", h.ADMIN)
    assert.equal(200, res.status)
    local d = res.body.data
    assert.is_string(d.access_token)
    assert.is_string(d.refresh_token)
    assert.equal(h.ADMIN.email, d.user.email)
    assert.is_nil(res.raw:find("password_hash"))
  end)

  it("yanlis parola ayni 401", function()
    local a = h.request("POST", "/auth/login", { email = h.ADMIN.email, password = "Yanlis123!" })
    assert.equal(401, a.status)
    assert.equal("INVALID_CREDENTIALS", h.code(a))
  end)

  it("/auth/me: token ile 200", function()
    local me = h.request("GET", "/auth/me", nil, admin.access_token)
    assert.equal(200, me.status)
    assert.equal(h.ADMIN.email, me.body.data.user.email)
  end)

  it("refresh rotasyonu", function()
    local s = h.login_admin()
    local r1 = h.request("POST", "/auth/refresh", { refresh_token = s.refresh_token })
    assert.equal(200, r1.status)
    local r2 = h.request("POST", "/auth/refresh", { refresh_token = s.refresh_token })
    assert.equal(401, r2.status)
    assert.equal("TOKEN_REVOKED", h.code(r2))
  end)

  it("logout 204 sonra reddedilir", function()
    local s = h.login_admin()
    assert.equal(204, h.request("POST", "/auth/logout", nil, s.access_token).status)
    assert.equal(401, h.request("GET", "/auth/me", nil, s.access_token).status)
  end)

  describe("forgot / reset password", function()
    local u, token
    setup(function() u = h.create_user(admin.access_token) end)
    it("var olan e-posta -> 202 ve mail", function()
      assert.equal(202, h.request("POST", "/auth/forgot-password", { email = u.email }).status)
      token = h.reset_token_from_mail(u.email)
      assert.is_string(token)
      assert.equal(64, #token)
    end)
    it("reset -> 204; eski parola 401, yeni 200", function()
      assert.equal(204, h.request("POST", "/auth/reset-password", { token = token, new_password = "Yeni1234!" }).status)
      assert.equal(401, h.request("POST", "/auth/login", { email = u.email, password = u.password }).status)
      assert.is_not_nil(h.login(u.email, "Yeni1234!"))
    end)
  end)
end)
