-- F22: table_browser filter -> sql builder mantigi (frontend filter_bar)
require("helper")
local app = require("app")
local json = require("json")

describe("table_browser filter", function()
  it("TABLE_BROWSER_OBJECT_SET sifirlar", function()
    local s = app.root_reducer(app.initial_state, { type = "TABLE_BROWSER_OBJECT_SET", object = { schema = "public", name = "customers" }, columns = {} })
    assert.equal("customers", s.table_browser.object.name)
    assert.equal(0, #s.table_browser.rows)
  end)

  it("TABLE_ROWS_REQUESTED filtre ve sort saklar", function()
    local fil = { { field = "email", op = "ILIKE", value = "%test%" } }
    local s = app.root_reducer(app.initial_state, { type = "TABLE_ROWS_REQUESTED", filters = fil, sort = "email" })
    assert.equal("email", s.table_browser.sort)
    assert.same(fil, s.table_browser.filters)
    assert.equal("loading", s.table_browser.status)
  end)

  it("optimistic rollback", function()
    local s = app.root_reducer(app.initial_state, { type = "TABLE_ROWS_LOADED", rows = { { id = "1", name = "a" } }, columns = {}, meta = {} })
    s = app.root_reducer(s, { type = "TABLE_ROW_UPDATE_OPTIMISTIC", id = "1", patch = { name = "b" } })
    assert.equal("b", s.table_browser.rows[1].name)
    s = app.root_reducer(s, { type = "TABLE_ROW_UPDATE_ROLLBACK", id = "1" })
    assert.equal("a", s.table_browser.rows[1].name)
  end)
end)

describe("table_browser safe_sql custom_where", function()
  it("noktali virgul iceren custom_where reddedilir (validasyon)", function()
    local validation = require("pg_shared.validation")
    local rule = validation.safe_sql()
    local ok, _ = rule.check("a=1; DROP TABLE t")
    assert.is_false(ok)
  end)
end)
