-- shared types: tip grubu ve operator tablosu (codd filtre kurallari)
local types = require("pg_shared.types")

describe("types.type_group", function()
  it("temel tipleri gruplar", function()
    assert.equal("numeric", types.type_group("int4"))
    assert.equal("numeric", types.type_group("numeric"))
    assert.equal("datetime", types.type_group("timestamptz"))
    assert.equal("text", types.type_group("uuid"))
    assert.equal("text", types.type_group("_int4", "ARRAY"))
    assert.equal("text", types.type_group("mood", "USER-DEFINED", true))
    assert.equal("json", types.type_group("jsonb"))
    assert.equal("binary", types.type_group("bytea"))
    assert.equal("other", types.type_group("interval"))
    assert.equal("other", types.type_group("point"))
  end)

  it("json ve binary yalnizca NULL operatorleri", function()
    assert.same({ "IS NULL", "IS NOT NULL" }, types.FILTER_OPS_BY_GROUP.json)
    assert.same({ "=", "!=", "LIKE", "ILIKE", "IS NULL", "IS NOT NULL" }, types.FILTER_OPS_BY_GROUP.text)
  end)
end)
