-- F27: hata konumu (position → satır/sütun) ve satır döndürmeyen komut etiketi
local query = require("db.target.query")

describe("query.line_col", function()
  it("konumu satır/sütuna çevirir", function()
    local line, col = query.line_col("SELECT 1\nFROM", 12)
    assert.equal(2, line); assert.equal(3, col)
    line, col = query.line_col("SELECT 1", 3)
    assert.equal(1, line); assert.equal(3, col)
  end)

  it("geçersiz konumda nil", function()
    assert.is_nil(query.line_col("SELECT 1", nil))
    assert.is_nil(query.line_col("SELECT 1", 0))
  end)
end)

describe("query.map_target_error", function()
  it("position alanını details'e taşır", function()
    local e = query.map_target_error({ code = "42601", message = "syntax error", position = 15 })
    assert.equal("BAD_REQUEST", e.code)
    assert.equal("42601", e.details.sqlstate)
    assert.equal(15, e.details.position)
  end)

  it("position yoksa alan eklenmez", function()
    local e = query.map_target_error({ code = "42P01", message = "x" })
    assert.is_nil(e.details.position)
  end)
end)

describe("query.command_tag", function()
  it("DML tek kelime, DDL iki kelime", function()
    assert.equal("INSERT", query.command_tag("insert into t values (1)"))
    assert.equal("UPDATE", query.command_tag("-- yorum\nUPDATE t SET a = 1"))
    assert.equal("CREATE TABLE", query.command_tag("CREATE TABLE t (id int)"))
    assert.equal("ALTER TABLE", query.command_tag("alter table t add c int"))
    assert.equal("affected", query.command_tag("   "))
  end)
end)
